# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aimeter < Formula
  desc "Terminal dashboard for AI provider usage and quota limits"
  homepage "https://github.com/cookiebinary1/aimeter"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cookiebinary1/aimeter/releases/download/v0.1.1/aimeter_0.1.1_darwin_amd64.tar.gz"
      sha256 "f1d488aff30e20d2c40c8189acd00161f3ecdd4272fe66100dd1c91719828871"

      define_method(:install) do
        bin.install "aimeter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cookiebinary1/aimeter/releases/download/v0.1.1/aimeter_0.1.1_darwin_arm64.tar.gz"
      sha256 "ca4fc493a05afc649f37553ec3efb0596c204fc1131c891cf5e9e2b4d52903eb"

      define_method(:install) do
        bin.install "aimeter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cookiebinary1/aimeter/releases/download/v0.1.1/aimeter_0.1.1_linux_amd64.tar.gz"
      sha256 "2cd6f22cc7007ca724edd2a89e13ebb63703504afb9c23cc8c22a6ca64fc85e9"
      define_method(:install) do
        bin.install "aimeter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cookiebinary1/aimeter/releases/download/v0.1.1/aimeter_0.1.1_linux_arm64.tar.gz"
      sha256 "623a611fdba0f734bdbf91e61c90633afe98387d6284ba1846df327c7dfe267c"
      define_method(:install) do
        bin.install "aimeter"
      end
    end
  end

  def caveats
    <<~EOS
      aimeter reads credentials from the environment, ~/.config/aimeter/credentials.json,
      the macOS keychain, and the native stores of Codex and Claude Code.
      Run `aimeter -show-creds` to see where each provider resolved from.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/aimeter -version")
  end
end
