# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aimeter < Formula
  desc "Terminal dashboard for AI provider usage and quota limits"
  homepage "https://github.com/cookiebinary1/aimeter"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cookiebinary1/aimeter/releases/download/v0.1.3/aimeter_0.1.3_darwin_amd64.tar.gz"
      sha256 "bf0eb3eb32b5cd8e716abf29aa362063cabb7e121c0a3da66a08ee31168d691c"

      define_method(:install) do
        bin.install "aimeter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cookiebinary1/aimeter/releases/download/v0.1.3/aimeter_0.1.3_darwin_arm64.tar.gz"
      sha256 "a817cb6dd4a5fec8c597dd0ead440346675e21f62570d8dd89f37b93772e6b54"

      define_method(:install) do
        bin.install "aimeter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cookiebinary1/aimeter/releases/download/v0.1.3/aimeter_0.1.3_linux_amd64.tar.gz"
      sha256 "f7129875176a41c20de05b5e8cfd4d5034c8d584ad5169dc976d822684b9d15e"
      define_method(:install) do
        bin.install "aimeter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cookiebinary1/aimeter/releases/download/v0.1.3/aimeter_0.1.3_linux_arm64.tar.gz"
      sha256 "bd86fec6b494346c71da756c8388fc038b93652110cd3ac10f9682f42308b58b"
      define_method(:install) do
        bin.install "aimeter"
      end
    end
  end

  def caveats
    <<~EOS
      aimeter reads credentials from the environment, ~/.config/aimeter/credentials.json,
      the macOS keychain, and the native stores of Codex and Claude Code.
      Run `aimeter -show-creds` to see where each provider resolved from.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/aimeter -version")
  end
end
