# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aimeter < Formula
  desc "Terminal dashboard for AI provider usage and quota limits"
  homepage "https://github.com/cookiebinary1/aimeter"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cookiebinary1/aimeter/releases/download/v0.1.2/aimeter_0.1.2_darwin_amd64.tar.gz"
      sha256 "c32837d9d9596d9aeb322376b1ed01478e814530325d6c1c7977fd1877c7c269"

      define_method(:install) do
        bin.install "aimeter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cookiebinary1/aimeter/releases/download/v0.1.2/aimeter_0.1.2_darwin_arm64.tar.gz"
      sha256 "dd207e377017b093771f881b9c505484d4a9008f526ba52e150a802d18819ca8"

      define_method(:install) do
        bin.install "aimeter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cookiebinary1/aimeter/releases/download/v0.1.2/aimeter_0.1.2_linux_amd64.tar.gz"
      sha256 "143e022ae292f287250347a6e4b71649d057d97752e05e853528cecea2aeb0b8"
      define_method(:install) do
        bin.install "aimeter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cookiebinary1/aimeter/releases/download/v0.1.2/aimeter_0.1.2_linux_arm64.tar.gz"
      sha256 "8e6f83fff01268782caf44a8b7dd91c9baa7439db3c6ccce77e0ea2ffde9a5af"
      define_method(:install) do
        bin.install "aimeter"
      end
    end
  end

  def caveats
    <<~EOS
      aimeter reads credentials from the environment, ~/.config/aimeter/credentials.json,
      the macOS keychain, and the native stores of Codex and Claude Code.
      Run `aimeter -show-creds` to see where each provider resolved from.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/aimeter -version")
  end
end
